apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  MYSQL_USER: {{ .Values.secret.mysqlUser | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.secret.mysqlPassword | b64enc | quote }}
