apiVersion: v1
kind: Service
metadata:
  name: flask-web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flask-web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000

