apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mysql.service.name }}-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.mysql.storage.storageClassName }}
  capacity:
    storage: {{ .Values.mysql.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mysql.storage.hostPath | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mysql.service.name }}-pvc
spec:
  storageClassName: {{ .Values.mysql.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}

