apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  # "root" được mã hóa Base64
  MYSQL_USER: a2hldXNlcg==               # kheuser
  MYSQL_PASSWORD: MTIz   
