apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mysql.service.name }}-config
data:
  my.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
    sql_mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    max_connections={{ .Values.mysql.config.maxConnections }}

