apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    app: {{ .Values.mysql.service.name }}
spec:
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
  clusterIP: {{ if .Values.mysql.service.headless }}None{{ else }}"{{ .Values.mysql.service.type }}"{{ end }}
  selector:
    app: {{ .Values.mysql.service.name }}

