
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask_login_demo
      MYSQL_USER: kheuser
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - /home/khe/Desktop/flask_docker_demo/mysql_data:/var/lib/mysql
    network_mode: bridge
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    network_mode: bridge

  web1:
    image: lamluongkhe/flask-redis-mysql:1.0
    environment:
      MYSQL_HOST: 192.168.0.10
      MYSQL_DATABASE: flask_login_demo
      MYSQL_USER: kheuser
      MYSQL_PASSWORD: 123
      REDIS_HOST: 192.168.0.10
      REDIS_PORT: 6379
      REDIS_DB: 0
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    network_mode: bridge

